### PR TITLE
Add Joined environment

### PR DESCRIPTION
**Pull request by ChristianWieck**
This PR:
- Adds a `CombineEnvironment` which combines the features of multiple environments into a single one.
- Add a method to `OfflineEnvironment` to directly combine it with another.

Open Points:
- The naming is not consitent yet. The method is called `extend` the environment `Combine`. I'm open to name suggestions here
- The same functionality could be useful for `IncrementalEnvironments`. Should we extend this implementation to cover them as well or do we define a seperate environment for that task?

### CODE REVIEW

**Comment by schmidma** [comment]
What do you think of something like `horizontal stack` or `join`

**Comment by ChristianWieck** [comment]
`horizontal stack` is technically correct, but doesn't sound "sexy". `join` is fine, but can easily be confused with `stack`

**Comment by schmidma** [comment]
How do we resolve this discussion? :smile:

**Comment by ChristianWieck** [comment]
Hold a vote? @newLabAspect and @mknitt what do you think? Which name is a good fit?

**Comment by newLabAspect** [comment]
I prefer being technically sound over being sexy. Thus, I would rather vote for `horizontal stack`. Nevertheless, in that case we should probably re-name `stack` to `vertical stack`. To have it shorter, another option would be `vstack` and `hstack`?

**Pull request merged**
